name: tests workflow

on: push

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install poetry
        uses: pipx install poetry

      - name: Add Poetry to PATH
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH
      
      - name: Instalando as dependências do projeto
        run: poetry install --no-root

      - name: Executar tests
        run: poetry run task test